module.exports = {
  Technical: {
    "Clive Chan": "Technical Director",
    "Benjamin Li": "Technical Integration Lead",
    "Jennifer Chen": "Technical PM",
    "Jimmy Zhou": "Technical PM (Mentor)",
    "Steven Phang": "Recruitment Lead",
    "Eldon Lobo": "Safety Captain",

    Mechanical: {
      "Cynthia Wang": "Mechanical Lead",
      "Jimmy Zhou": "Mechanical Lead",
      "Attilio Ravani": "Mechanical Lead",
      "Emrys Halbertsma": "Mechanical Lead",
      "Pascal Voyer-Nguyen": "Mechanical Lead",
      "Jennifer Chen": "Mechanical Lead",
      "Kenton Tran": "",
      "Natalie Thiessen": "",
      "Mohammad Yehya Qureshi": "",
      "Nicholas Drazso": "",
      "Hank Wu": "",
      "Bryan Poon": "",
      "Nicholas Gisone": "",
      "Praven Vikneswararaja": "",
      "Samuel Roberge-Arnott": "",
      "Benjamin Li": "",
      "Phillip Shahviri": "",
      "James Bates": "",
      "Jason Jia": "",
      "Theo Schlotzhauer": "",
    },
    Electrical: {
      "Alfonso Faria Espinoza": "Electrical Lead",
      "Ben Hu": "Electrical Lead",
      "Jason Wu": "Electrical Lead",
      "Neel Bhavsar": "",
      "Tony Wang": "",
      "Chawthri": "",
      "Prajakta Muley": "",
      "Gurubaani Monga": "",
      "Linda Mao": "",
      "Jordan Lau": "",
      "Avani Joshi": "",
      "Connor McCallum": "",
      "Andrea Parra": "",
    },
    Software: {
      "Clive Chan": "Technical Director, Software Lead",
      "Steven Xiong": "Web Lead",
      "Jerin Raisa": "Web Co-Lead",
      "Lynn Kim": "Web Co-Lead",
      "Anne Chung": "",
      "Cameron Kinsella": "",
      "Matthew Wang": "",
      "Johnny Chen": "",
      "Alex Aronovici": "",
      "Andrew Liu": "",
      "Megan Tse": "",
      "Rhea Mehta": "",
      "George Yuan": "",
      "Kai Yuan Chi": "",
      "Kevin": "",
      "Sergiu Pocol": "",
      "Jainish Mehta": "",
      "Tamim Khan": "",
      "Zafin Hassan": "",
      "Emily Louie": "",
      "Willa Kong": "",
      "Stephen Lin": "",
      "Michael Pu": "",
      "Yeshu Jain": "",
      "Catherine Lee": "",
      "Jeff Ma": "",
      "Ameen Khan": "",
    }
  },
  Admin: {
    Business: {
      "Krista Porter": "Business Lead",
      "Yu An Chen": "",
      "Irina Chubarova": "",
      "Erik Tran": "",
      "Khanh Do": "",
      "Shaurya Saxena": "",
      "Quinlin Wu": "",
    },
    Infrastructure: {
      "Ben Busca": "Infrastructure Lead",
    }
  }
};
