module.exports = {
  "Technical": {
    "Clive Chan": "Technical Director",
    "Chawthri Kanagarasa": "Offstream Technical Director",
    "Emrys Halbertsma": "Project Manager",
    "Daniel Ingriselli": "Mechanical Lead",
    "Donovan Kwong": "Offstream Mechanical Lead",
    "Navreet Dhillon": "Mechanical Co-op",
    "Pneumatics": {
      "Celeste Ozimek-Newman": "Pneumatics Lead",
      "Theodore Schlotzhauer": "Pneumatics Lead",
      "Benjamin Li": "Member",
      "Vihangi Mehta": "Member",
      "Dasha Korotkova": "Member",
      "Clara Tsai": "Member",
      "Gagan Malik": "Member",
    },
    "Structures": {
      "Attilio Ravani": "Structures Lead",
      "Adam Linton": "Senior Member",
      "Mike Domm": "Member",
      "Kaitlyn Lee": "Member",
      "Paul Shen": "Member",
    },
    "Linear Induction Motor": {
      "Ben Hu": "LIM Lead",
      "Conrad Masak": "LIM Lead",
      "Shreshth Mehra": "Member",
      "Oscar Manuel Carreno-Molina": "Member",
    },
    "Electrical": {
      "Wazer Rehman": "Electrical Lead",
      "Jordan Lau": "Senior Member",
      "Stephen He": "Member",
      "Sam MacLeod": "Member",
      "Mingze Jin": "Member",
      "Bradley Brown": "Member",
      "Clayton Sockabasin": "Member",
      "Sumaiya Islam": "Member",
      "Nick Yu": "Member",
    },
    "Software": {
      "Deep Dhillon": "Software Lead",
      "Aakash Ravichandran": "Senior Member",
      "Harry Zhang": "Senior Member",
      "Galen Sprout": "Member",
      "Ian Ramzy": "Member",
      "Kexin (Katie) Chen": "Member",
      "Siddharth Bhattacharjee": "Member",
      "Thao Tran": "Member",
      "Priyanka Hariharan": "Member",
      "Steven Feng": "Member",
      "Vishesh Gupta": "Member",
    },
  },
  "Admin": {
    "Emile Patry": "Admin Lead",
    "Marketing": {
      "Ariana Mayer": "Marketing Lead",
      "Billie Chow": "Member",
      "Irina Chubarova": "Member",
      "Jared Wou": "Member",
      "Kevin Tang": "Member",
    },
    "Sponsorship": {
      "Soham Suvarnkar": "Sponsorship Lead",
      "Justin Hammond": "Sponsorship Lead",
      "Aleena Singh": "Member",
      "John Glennie": "Member",
      "Anushka Tayal": "Member",
      "James Bury": "Member",
    },
    "Finance": {
      "Zahra Kamal": "Finance Lead",
      "Maharram Mansimov": "Member",
    },
    "Infrastructure": {
      "Candy Lee": "Infrastructure Lead",
      "Yuvna Apajee": "Infrastructure Lead",
      "Trisha Singh": "Member",
      "Christina Sugiura": "Member",
      "Angel Novillo": "Member",
      "Pranav Sairam": "Member",
      "Marijo Arias ": "Member",
      "Michael Cairns": "Member",
      "Michelle Stepanek": "Member",
      "Jack Codini": "Member",
    },
  },
  "Advisors": {
    "Serhiy Yarusevych": "Faculty Advisor",
    "Victor Qian": "Alum Advisor",
    "Dallyn Wynnychuk": "Alum Advisor",
    "Jason Pan": "Alum Advisor",
    "Nicholas Jelich": "Alum Advisor",
    "Jimmy Zhou": "Alum Advisor",
  },
}
