module.exports = {
  Technical: {
    "Clive Chan": "Technical Director",
    "Benjamin Li": "Technical Integration Lead",
    "Jennifer Chen": "Technical PM",
    "Steven Phang": "Recruitment Lead",

    Mechanical: {
      "Clara Tsai": "Mechanical Co-Lead",
      "Emrys Halbertsma": "Mechanical Co-Lead",
      "Arnav Garcha": "Mechanical Lead (Mentor)",
      "Hank Wu": "LIM Lead",
      "Bryan Poon": "LIM Integration Lead",
      "Nicholas Gisone": "Low Voltage Lead",
      "Kshitij Kadiya": "Motor Controller Lead",
      "Jackie Hane": "",
      "Praven Vikneswararaja": "",
      "Ashley Cho": "",
      "Selina Huang": "",
      "Muhammad Ameen Yaseen": "",
      "Emily Tou": "",
      "Sam MacLeod": "",
      "Angela Nguyen": "",
      "Caleb Ng": "",
      "Saksham Malik": "",
      "Daniel Ingriselli": "",
      "Lyka Pinlac": "",
      "Andrew Nguyen": "",
      "Jimmy Zhou": "",
      "Mohammad Yehya Qureshi ": "",
      "Jacky He": "",
      "Marcus Li": "",
      "Dasha Korotkova": "",
      "Yali Chen": ""
    },
    Electrical: {
      "Linda Mao": "Electrical Lead",
      "Chawthri Kanagarasa": "LIM Integration Lead",
      "Connor McCallum": "Low Voltage Lead",
      "Jason Wu": "Motor Controller Lead",
      "Andrea Parra": "",
      "Sonny Song": "",
      "Jessica Lui": "",
      "Ryan Mah": "",
      "Steven Zhou": "",
      "Alfonso Faria Espinoza": "",
      "John Wu": "",
      "Neel Bhavsar": "",
      "Gaston Lee": "",
      "Luke Doria": "",
      "Ryun Kim": "",
      "Aylon Porat": "",
      "Alicia Gaetan": "",
      "David Liu": "",
      "Emmy Ni": "",
      "David Zhang": "",
      "Karla Castro": "",
      "Kaitlyn Tse": "",
      "Tony Wang": "",
      "Tristan Le": "",
      "Gurubaani Monga": "",
      "Ian K. Ross": ""
    },
    Software: {
      "Clive Chan": "Technical Director, Software Lead",
      "Sergiu Pocol": "Desktop Lead; Network & Communications Lead",
      "Kamran Tayyab": "Embedded Lead",
      "Kevin Bai": "Team Hub Lead",
      "Jerin Raisa": "Web Co-Lead",
      "Lynn Kim": "Web Co-Lead",
      "Rutvik Bhende": "",
      "Anne Chung": "",
      "Ana Ramon": "",
      "Andrew Liu": "",
      "Johnny Chen": "",
      "Adrian Cerejo": "",
      "Matthew Wang": "",
      "Carson Tang": "",
      "Tamim Mahmud Khan": "",
      "Aditya Subramanian": "",
      "Yash Dani": "",
      "James Chen": "",
      "Kathleen Liang": "",
      "KaiYuan Chi": "",
      "Jeff Ma": "",
      "Quinn Hodges": "",
      "Younghwan Kim": "",
      "Mir Zafin Hassan": "",
      "Marko Arezina": "",
      "Kevin Li": "",
      "Yeshu Jain": "",
      "Talia Wang": "",
      "Alex Aronovici": "",
      "Aditya Srinivasan": "",
      "Nafis Hasnain": "",
      "Nathan Au": "",
      "Garrick Clarke": "",
      "Michael Pu": "",
      "Catherine Lee": "",
      "Dea Chaudhery ": "",
      "Cyrus Gandevia": "",
      "Sally Zhou": "",
      "George Yuan": "",
      "Banin Abrar": "",
      "Vishesh Gupta": "",
      "Lyka Pinlac": ""
    }
  },
  Admin: {
    Business: {
      "Anton Chow": "Business Lead",
      "Quinlin Wu": "Marketing Lead",
      "Ariana Mayer": "Marketing Lead (mentor)",
      "Prithika Hariharan": "",
      "Huy Nguyen": ""
    },
    Infrastructure: {
      "Yuvna Apajee": "",
      "Christie Cho": "",
      "Sadia Tashnuva": "",
      "Ivan Lau": "",
      "Nancy Situ": ""
    }
  }
};
