module.exports = {
  "Technical": {
    "Clive Chan": "Technical Director",
    "Benjamin Li": "Technical Integration Lead",
    "Jennifer Chen": "Technical PM",
    "Steven Phang": "Recruitment Lead",

    "Mechanical": {
      "Clara Tsai": "Mechanical Co-Lead",
      "Emrys Halbertsma": "Mechanical Co-Lead",
      "Arnav Garcha": "Mechanical Lead (Mentor)",
      "Hank Wu": "LIM Lead",
      "Bryan Poon": "LIM Integration Lead",
      "Nicholas Gisone": "Low Voltage Lead",
      "Kshitij Kadiya": "Motor Controller Lead",
      "Jackie Hane": "Member",
      "Praven Vikneswararaja": "Member",
      "Ashley Cho": "Member",
      "Selina Huang": "Member",
      "Muhammad Ameen Yaseen": "Member",
      "Emily Tou": "Member",
      "Sam MacLeod": "Member",
      "Angela Nguyen": "Member",
      "Caleb Ng": "Member",
      "Saksham Malik": "Member",
      "Daniel Ingriselli": "Member",
      "Lyka Pinlac": "Member",
      "Andrew Nguyen": "Member",
      "Jimmy Zhou": "Member",
      "Mohammad Yehya Qureshi ": "Member",
      "Jacky He": "Member",
      "Marcus Li": "Member",
      "Dasha Korotkova": "Member",
      "Yali Chen": "Member",
    },
    "Electrical": {
      "Linda Mao": "Electrical Lead",
      "Chawthri Kanagarasa": "LIM Integration Lead",
      "Connor McCallum": "Low Voltage Lead",
      "Jason Wu": "Motor Controller Lead",
      "Andrea Parra": "Member",
      "Sonny Song": "Member",
      "Jessica Lui": "Member",
      "Ryan Mah": "Member",
      "Steven Zhou": "Member",
      "Alfonso Faria Espinoza": "Member",
      "John Wu": "Member",
      "Neel Bhavsar": "Member",
      "Gaston Lee": "Member",
      "Luke Doria": "Member",
      "Ryun Kim": "Member",
      "Aylon Porat": "Member",
      "Alicia Gaetan": "Member",
      "David Liu": "Member",
      "Emmy Ni": "Member",
      "David Zhang": "Member",
      "Karla Castro": "Member",
      "Kaitlyn Tse": "Member",
      "Tony Wang": "Member",
      "Tristan Le": "Member",
      "Gurubaani Monga": "Member",
      "Ian K. Ross": "Member",
    },
    "Software": {
      "Clive Chan": "Technical Director, Software Lead",
      "Sergiu Pocol": "Desktop Lead; Network & Communications Lead",
      "Kamran Tayyab": "Embedded Lead",
      "Kevin Bai": "Team Hub Lead",
      "Jerin Raisa": "Web Co-Lead",
      "Lynn Kim": "Web Co-Lead",
      "Rutvik Bhende": "Member",
      "Anne Chung": "Member",
      "Ana Ramon": "Member",
      "Johnny Chen": "Member",
      "Adrian Cerejo": "Member",
      "Matthew Wang": "Member",
      "Carson Tang": "Member",
      "Tamim Mahmud Khan": "Member",
      "Aditya Subramanian": "Member",
      "Yash Dani": "Member",
      "James Chen": "Member",
      "Kathleen Liang": "Member",
      "KaiYuan Chi": "Member",
      "Jeff Ma": "Member",
      "Quinn Hodges": "Member",
      "Younghwan Kim": "Member",
      "Mir Zafin Hassan": "Member",
      "Marko Arezina": "Member",
      "Kevin Li": "Member",
      "Yeshu Jain": "Member",
      "Talia Wang": "Member",
      "Alex Aronovici": "Member",
      "Aditya Srinivasan": "Member",
      "Nafis Hasnain": "Member",
      "Nathan Au": "Member",
      "Garrick Clarke": "Member",
      "Michael Pu": "Member",
      "Catherine Lee": "Member",
      "Dea Chaudhery ": "Member",
      "Cyrus Gandevia": "Member",
      "Sally Zhou": "Member",
      "George Yuan": "Member",
      "Banin Abrar": "Member",
      "Vishesh Gupta": "Member",
      "Lyka Pinlac": "Member",
    },
  },
   "Business": {
      "Anton Chow": "Business Lead",
      "Quinlin Wu": "Marketing Lead",
      "Ariana Mayer": "Marketing Lead (mentor)",
      "Prithika Hariharan": "Member",
      "Huy Nguyen": "Member",
    }, 
    "Infrastructure": {
      "Yuvna Apajee": "Member",
      "Christie Cho": "Member",
      "Sadia Tashnuva": "Member",
      "Ivan Lau": "Member",
      "Nancy Situ": "Member",
    },
}
