module.exports = {
  Technical: {
    "Emrys Halbertsma": "Technical PM",
    "Jennifer Chen": "Technical PM",
    "Jimmy Zhou": "Technical Integration Lead",
    "Pascal Voyer-Nguyen": "Technical Integration Lead",
    "Clive Chan": "Technical Director (Mentor)",
    "Linda Mao": "Technical Director (Mentor)",

    Mechanical: {
      "Cynthia Wang": "Mechanical Lead",
      "Attilio Ravani": "Mechanical (Mentor)",
      "Ben Li": "Mechanical (Mentor)",
      "Jimmy Zhou": "Mechanical (Mentor)",
      "Pascal Voyer-Nguyen": "Mechanical (Mentor)",
      "Emrys Halbertsma": "Mechanical (Mentor)",
      "Jennifer Chen": "Mechanical (Mentor)",
      "Kenton Tran": "",
      "Natalie Thiessen": "",
      "Mohammad Yehya Qureshi": "",
      "Nicholas Drazso": "",
      "Hank Wu": "",
      "Bryan Poon": "",
      "Nicholas Gisone": "",
      "Praven Vikneswararaja": "",
      "Samuel Roberge-Arnott": "",
      "Benjamin Li": "",
      "Phillip Shahviri": "",
      "James Bates": "",
      "Jason Jia": "",
      "Theo Schlotzhauer": "",
    },
    Electrical: {
      "Ben Hu": "Electrical Lead",
      "Alfonso Faria Espinoza": "BMS Lead",
      "Jason Wu": "Motor Control Lead",
      "Jordan Lau": "Electrical (Mentor)",
      "Linda Mao": "Electrical (Mentor)",
      "Connor McCallum": "Electrical (Mentor)",
      "Neel Bhavsar": "",
      "Tony Wang": "",
      "Chawthri": "",
      "Prajakta Muley": "",
      "Gurubaani Monga": "",
      "Avani Joshi": "",
      "Andrea Parra": "",
    },
    Software: {
      "Kam Tayyab": "Software Lead",
      "Alex Aronovici": "Desktop Lead",
      "Steven Xiong": "Team Hub Lead",
      "Lynn Kim": "Web Co-Lead",
      "Jerin Raisa": "Web Co-Lead",
      "Clive Chan": "Software (Mentor)",
      "Rhea Mehta": "",
      "Willa Kong": "",
      "Stephen Lin": "",
      "Yeshu Jain": "",
      "Anne Chung": "",
      "Cameron Kinsella": "",
      "Matthew Wang": "",
      "Johnny Chen": "",
      "Andrew Liu": "",
      "Megan Tse": "",
      "George Yuan": "",
      "Kai Yuan Chi": "",
      "Kevin": "",
      "Sergiu Pocol": "",
      "Jainish Mehta": "",
      "Tamim Khan": "",
      "Zafin Hassan": "",
      "Emily Louie": "",
      "Michael Pu": "",
      "Catherine Lee": "",
      "Jeff Ma": "",
      "Ameen Khan": "",
    }
  },
  Admin: {
    Business: {
      "Krista Porter": "Business and Finance Lead",
      "Anton Chow": "Business (Mentor)",
      "Emrys Halbertsma": "Business (Mentor)",
      "Yu An Chen": "",
      "Irina Chubarova": "",
      "Erik Tran": "",
      "Khanh Do": "",
      "Shaurya Saxena": "",
      "Quinlin Wu": "",
    },
    Infrastructure: {
      "Ben Busca": "Infrastructure Lead",
    }
  }
};
